services:
  django:
    build:
      context: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000

    command: ["sh", "./start.sh"]

    env_file:
      - .env
    environment:
      - DB_HOST=database
      - DB_NAME=testdb
      - DB_USER=testuser
      - DB_PASS=pass

    depends_on:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  database: